version: '3.8'
services:
  neo4j:
    image: neo4j:5.10
    ports:
      - "37474:7474"
      - "37687:7687"
    volumes:
      - lf-neo4j-data:/data
    restart: always
    environment:
      - NEO4J_AUTH=neo4j/test_password
      - NEO4J_server_memory_pagecache_size=512M
      - NEO4J_server.memory.heap.initial_size=512M
      - NEO4J_server_memory_heap_max__size=512M
      - NEO4J_PLUGINS=["apoc"]

volumes:
  lf-neo4j-data:
    driver: local