export enum AssignmentStatus {
  CANCELLED = 'CANCELLED',
  WAITING_FOR_DRIVER_ASSIGNMENT = 'WAITING_FOR_DRIVER_ASSIGNMENT',
  DRIVER_ASSIGNMENT_FAILED = 'DRIVER_ASSIGNMENT_FAILED',
  ON_THE_WAY = 'ON_THE_WAY',
}
